// Case studies and client websites shown on the home page.
// Kept out of the client component so the server can also build structured data from them.

export const projects = [
  {
    id: 1,
    index: "01",
    title: "Multi-Agent Document Intelligence",
    subtitle: "Contract Analysis System",
    tagline: "Enterprise AI that reads, reasons, and reports — at scale.",
    color: "#6366f1",
    colorDim: "#6366f120",
    year: "2024",
    category: "AI Systems",
    overview: "Enterprise organizations spend significant time reviewing contracts, legal agreements, and business documents manually. Traditional LLM-based chatbots often struggle with long documents, structured outputs, and complex reasoning across multiple sections. The goal of this project was to build a production-ready multi-agent platform capable of analyzing contracts, extracting key clauses, identifying risks, and generating structured summaries through collaborative AI agents.",
    problem: "Legal and procurement teams manually review lengthy contracts, leading to slow turnaround times and inconsistent analysis. Existing chatbot-style solutions often lose context in long documents, produce inconsistent outputs, and cannot reason through multiple document sections simultaneously.",
    solution: "I designed a multi-agent architecture where specialized AI agents collaborate to complete different stages of document analysis. Instead of relying on a single LLM prompt, the workflow distributes responsibilities across multiple autonomous agents coordinated through LangGraph — each focusing on document understanding, clause extraction, risk identification, summary generation, and response validation. The final output is streamed back in real time with structured JSON responses.",
    architecture: [
      { label: "PDF Upload", icon: "📄" },
      { label: "Parser", icon: "⚙️" },
      { label: "Chunking", icon: "✂️" },
      { label: "Retriever", icon: "🔍" },
      { label: "Planner Agent", icon: "🧭" },
      { label: "Clause Agent", icon: "📋" },
      { label: "Risk Agent", icon: "⚠️" },
      { label: "Summary Agent", icon: "📝" },
      { label: "Aggregator", icon: "🔗" },
      { label: "Structured Output", icon: "✅" },
      { label: "Frontend", icon: "🖥️" },
    ],
    features: [
      "Multi-agent orchestration via LangGraph",
      "Streaming responses using Server-Sent Events",
      "Prompt caching for cost optimization",
      "Structured outputs with Pydantic",
      "LangSmith tracing & observability",
      "Conversation memory across sessions",
      "Modular, swappable agent architecture",
    ],
    tech: ["LangGraph", "OpenAI GPT-4o", "FastAPI", "Next.js", "TypeScript", "LangSmith", "Pydantic"],
    results: [
      { value: "50%", label: "LLM cost reduction via prompt caching" },
      { value: "∞", label: "Real-time streaming responses" },
      { value: "5+", label: "Specialized agents collaborating" },
      { value: "100%", label: "Structured JSON outputs" },
    ],
    role: "Designed the complete architecture, developed the backend orchestration using LangGraph, implemented streaming APIs, structured outputs, and integrated frontend interactions.",
    github: "https://github.com/Harsh1652/Multi-Agent-Document-Intelligence",
    demo: "https://multi-agent-document-intelligence.vercel.app/",
  },
  {
    id: 2,
    index: "02",
    title: "Stock Research Agent",
    subtitle: "Autonomous Financial Analysis",
    tagline: "5 AI agents. Full market research. 30 seconds.",
    color: "#38bdf8",
    colorDim: "#38bdf820",
    year: "2024",
    category: "AI Systems",
    overview: "Investment research requires gathering information from multiple independent sources including financial statements, company fundamentals, market news, and investor sentiment.\n\nThis project automates that workflow using multiple AI agents working in parallel to generate comprehensive research reports.",
    problem: "Retail investors spend hours switching between finance websites, news platforms, and earnings reports before making investment decisions.\n\nThere was no single system capable of consolidating all this information into an explainable AI-generated report.",
    solution: "Built a five-agent research system where each AI agent specializes in one domain.\n\nInstead of sequential processing, agents execute in parallel, significantly reducing response time. The final recommendation is generated only after aggregating outputs from all research agents.",
    architecture: [
      { label: "Ticker", icon: "💬" },
      { label: "Planner", icon: "🧭" },
      { label: "News Agent", icon: "📰" },
      { label: "Financial Agent", icon: "📊" },
      { label: "Technical Agent", icon: "📈" },
      { label: "Sentiment Agent", icon: "🎯" },
      { label: "Company Agent", icon: "🏢" },
      { label: "Aggregator", icon: "🔗" },
      { label: "Buy / Hold / Sell Report", icon: "✅" },
    ],
    features: [
      "Parallel execution",
      "Multi-agent reasoning",
      "LangGraph reducers",
      "LangSmith observability",
      "Cost tracking",
      "Portfolio-ready reports",
    ],
    tech: ["Python", "LangGraph", "FastAPI", "OpenAI", "Tavily", "yfinance", "LangSmith"],
    results: [
      { value: "~30s", label: "Report generation time" },
      { value: "5", label: "Concurrent research streams" },
      { value: "$0.0003", label: "Average cost per report" },
    ],
    role: "Designed the agent workflow, implemented state management, integrated external APIs, and optimized latency using parallel graph execution.",
    github: "https://github.com/Harsh1652/Stock_Research_Agent/tree/main",
    demo: "https://stock-research-agent-smoky.vercel.app/",
  },
  {
    id: 3,
    index: "03",
    title: "Regulatory Document Intelligence",
    subtitle: "Enterprise RAG Platform",
    tagline: "300-page PDFs. Instant, accurate, compliant answers.",
    color: "#34d399",
    colorDim: "#34d39920",
    year: "2024",
    category: "AI Systems",
    overview: "Regulatory filings such as RHPs and DRHPs often exceed hundreds of pages, making manual information retrieval inefficient.\n\nThis platform enables organizations to query large regulatory documents using Retrieval-Augmented Generation (RAG).",
    problem: "Business analysts spend significant time searching through lengthy regulatory filings for specific information.\n\nTraditional keyword search lacks semantic understanding and often misses relevant sections.",
    solution: "Developed a production-grade RAG platform capable of ingesting large PDF documents, generating embeddings, and answering natural language queries with contextual accuracy.\n\nThe platform supports multiple organizations while maintaining complete workspace isolation.",
    architecture: [
      { label: "PDF", icon: "📄" },
      { label: "Chunking", icon: "✂️" },
      { label: "Embedding", icon: "🔢" },
      { label: "Pinecone", icon: "🌲" },
      { label: "Retriever", icon: "🔍" },
      { label: "OpenAI", icon: "🤖" },
      { label: "Response", icon: "✅" },
    ],
    features: [
      "Recursive chunking",
      "Semantic search",
      "Multi-tenant architecture",
      "JWT authentication",
      "RBAC",
      "Automated ingestion",
      "Workspace isolation",
    ],
    tech: ["Node.js", "Express", "MongoDB", "Pinecone", "OpenAI", "Cohere", "n8n", "React", "TypeScript"],
    results: [
      { value: "300+", label: "Page PDFs supported" },
      { value: "<3s", label: "Query latency" },
      { value: "80%", label: "Manual effort reduced" },
    ],
    role: "Designed and developed the backend architecture, ingestion pipeline, retrieval system, authentication, and AI integration.",
    github: "https://github.com/Harsh1652/ai-regulatory-document-intelligence",
    demo: "",
  },
];

export const sites = [
  {
    name: "Invisigent", url: "https://invisigent.com",
    description: "Marketing website for an AI startup — modern design system, optimized layouts, and a fast, responsive user experience.",
    tech: ["Next.js", "React", "TypeScript", "CSS"],
    color: "#818cf8",
    preview: { title: "Invisigent", tagline: "Intelligent business solutions powered by AI" },
    metrics: ["Responsive", "Performance Optimized", "SEO-Friendly"],
    caseStudy: {
      overview: "Invisigent is an AI startup focused on building intelligent business solutions. I developed the company's marketing website with an emphasis on performance, responsiveness, and a modern user experience that reflects the company's AI-first identity.",
      problem: "The company needed a professional web presence to communicate its services, establish credibility with potential clients, and support business development.",
      solution: "Built a responsive marketing website featuring a modern design system, optimized layouts, reusable UI components, and performance-focused implementation.\n\nThe website was designed to scale with future product offerings while maintaining fast load times across devices.",
      features: ["Responsive design", "Modern landing pages", "Optimized performance", "Reusable components", "SEO-friendly structure"],
      tech: ["Next.js", "React", "TypeScript", "HTML", "CSS"],
      role: "Designed and developed the frontend, implemented responsive layouts, optimized performance, and collaborated with the team on branding and user experience.",
    },
  },
  {
    name: "Baalaji Exports", url: "https://www.baalajiexports.com/",
    description: "Corporate exports website with a custom SEO management panel — admins update metadata and content without touching code.",
    tech: ["Next.js", "React", "Node.js", "MongoDB"],
    color: "#f59e0b",
    preview: { title: "Baalaji Exports", tagline: "Quality exports to 20+ countries worldwide" },
    metrics: ["SEO Dashboard", "Admin Panel", "MongoDB"],
    caseStudy: {
      overview: "Baalaji Exports required both a public-facing business website and an internal system for managing SEO content efficiently.\n\nBeyond developing the website, I also built a custom SEO management panel that allows administrators to update metadata and website content without modifying code.",
      problem: "Updating SEO content manually across multiple pages was time-consuming and required developer involvement.",
      solution: "Developed a responsive corporate website alongside a custom admin panel connected to MongoDB.\n\nThe internal dashboard enables non-technical users to manage SEO metadata and website content dynamically.",
      features: ["Responsive corporate website", "SEO management dashboard", "Dynamic metadata", "MongoDB integration", "Content management"],
      tech: ["Next.js", "React", "Node.js", "MongoDB", "REST APIs"],
      results: ["Eliminated manual code changes for SEO updates.", "Simplified website maintenance through an internal admin interface.", "Improved scalability for future content updates."],
      role: "Designed, developed, and deployed both the website and the custom SEO management platform.",
    },
  },
  {
    name: "ArtCart by Swati", url: "https://artcartbyswati.in/",
    description: "Shopify storefront for curated artwork and home décor — custom theme, mobile-first design, and a frictionless checkout aligned with the brand's Instagram identity.",
    tech: ["Shopify", "Liquid", "HTML", "CSS", "JavaScript"],
    color: "#ec4899",
    preview: { title: "ArtCart by Swati", tagline: "Curated art for the discerning collector" },
    metrics: ["Custom Theme", "Mobile-First", "Instagram-Friendly"],
    caseStudy: {
      overview: "ArtCart by Swati is a Shopify-powered e-commerce store for curated artwork and home décor products. The goal was to create a premium shopping experience while maintaining a seamless integration with the founder's existing Instagram-driven sales strategy.",
      problem: "The business relied heavily on Instagram for customer engagement, but required a dedicated e-commerce storefront to improve product discovery, build customer trust, and streamline online purchases.",
      solution: "Customized a Shopify storefront with a clean, modern design focused on visual storytelling, mobile responsiveness, and a frictionless shopping experience. The site was optimized to complement social media traffic while leveraging Shopify's built-in commerce capabilities.",
      features: ["Custom Shopify theme customization", "Mobile-first responsive design", "Optimized product catalog", "Seamless checkout experience", "Instagram-friendly landing experience", "Performance optimization"],
      tech: ["Shopify", "Liquid", "HTML", "CSS", "JavaScript"],
      results: ["Delivered a polished online storefront aligned with the brand's visual identity.", "Improved the customer journey from Instagram discovery to product purchase.", "Enabled the founder to manage products, inventory, and orders directly through Shopify."],
      role: "Customized the Shopify storefront, implemented the frontend experience, optimized responsiveness and performance, and collaborated closely with the founder to translate the brand's Instagram presence into a cohesive e-commerce experience.",
    },
  },
];

export type Project = (typeof projects)[number];
export type Site = (typeof sites)[number];
